modulePacks = [ "standard" ]
modules = []
packages = []

[host]
name = "igg"
arch = "x86_64"
os = "linux" # linux for nixos or darwin for macos

[user]
name = "jdoe"
fullname = "John Doe"
email = "jdoe@email.com"
