modulePacks = [ "standard" ]
modules = []
packages = []

[host]
name = "igg"
arch = "x86_64"
os = "linux" # linux for nixos or darwin for macos
virtualized = true # only applicable to linux, defaults to false

[user]
name = "jdoe"
fullname = "John Doe"
email = "jdoe@email.com"

[user.work.company]
email = "jdoe@company.com"

[user.work.company.git]
initBranch = "master" # defaults to main
